p8105_hw2_jr4392
================
Junyi Ren
2023-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

\##Problem 1

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |>
  select(year, month, everything(), -day, -prez_dem, -prez_gop)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

``` r
snp = 
  read_csv("./fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  select(year, month, close) |>
  mutate(year = ifelse(year >= 50, 1900 + year, 2000+ year)) |>
  mutate(month = month.name[month])
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

``` r
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

## Problem 2

``` r
trash_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 1) |>
    janitor::clean_names() |>
    select(-x15, -x16)|>
  head(-1) |>
    mutate(
    homes_powered = weight_tons * 500 / 30) |>
   mutate(year = as.numeric(year)) |>
  mutate(Trash_Wheel = "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

The dataset `trash_data` has 584 observations and 15 variables. The
`weight_tons` is the weight of trash in tons. The `homes_powered` is
calculated by trash `weight_tons`. On the 2014-05-16, dumpster 1 has
4.31 tons of trash, which could power average 71.8333333 homes.

``` r
professor_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 2) |>
  janitor::clean_names() |>
    head(-1) |>
    mutate(
    homes_powered = weight_tons * 500 / 30) |>
    mutate(year = as.numeric(year)) |>
   mutate(Trash_Wheel = "Professor Trash Wheel")
sum(professor_data$weight_tons)
```

    ## [1] 216.26

The dataset `professor_data` has 106 observations and 14 variables. The
total weight of trash collected by Professor Trash Wheel is 216.26 tons.

``` r
gwynnda_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 4) |> 
  janitor::clean_names() |>
  head(-2) |>
  mutate(
    homes_powered = weight_tons * 500 / 30) |>
    mutate(year = as.numeric(year)) |>
   mutate(Trash_Wheel = "Gwynnda Trash Wheel")
sum(filter(gwynnda_data, month == "July" & year == 2021)$cigarette_butts)
```

    ## [1] 16300

The dataset `gwynnda_data` has 155 observations and 13 variables. The
total number of cigarette butts collected by Gwynnda in July of 2021 is
16,300.

``` r
merge_trash_wheel_data = 
  bind_rows(trash_data, professor_data, gwynnda_data)
```

The combined dataset `merge_trash_wheel_data` has 845 observations and
15 variables.

## Problem 3

``` r
baseline_df = 
  read_csv("./data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
        sex, 
        0 ~ "female", 
        1 ~ "male"),
    sex = as.factor(sex), 
    apoe4 = 
      case_match(
        apoe4, 
        0 ~ "APOE4 non-carrier",
        1 ~ "APOE4 carrier"),
    apoe4 = as.factor(apoe4) ) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_df = 
  baseline_df |>
  mutate(age_at_onset = as.numeric(age_at_onset)) |>
  filter(age_at_onset > current_age | is.na(age_at_onset))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `age_at_onset = as.numeric(age_at_onset)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
mean(mci_baseline_df$current_age)
```

    ## [1] 65.0286

``` r
nrow(filter(mci_baseline_df,sex == "female" & apoe4 == "APOE4 carrier"))/nrow(filter(mci_baseline_df,sex == "female"))*100
```

    ## [1] 30

The dataset has 483 observations and 6 variables. Each observation has
an id number, age at the study baseline, sex, education, apoe4 carrier
or non_carrier, and age at the onset of MCI. In the process of importing
`baseline_df`,the first line is skipped and make the second line as the
header. Sex and apoe4 values are changed to character with explanation
instead of numbers(factors). In `mci_baseline_df`, data for no MCI
people is removed.

483 participants were recruited, of these, 479 develop MCI. The average
baseline age is 65.0286. The proportion of women in the study are APOE4
carriers is 30%.

``` r
amyloid_df = 
  read_csv("./data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id  = study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The dataset has 487 observations and 6 variables. In the process of
importing `amyloid_df`,the first line is skipped and make the second
line as the header.

``` r
anti_join(mci_baseline_df, amyloid_df, by = "id")
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4             age_at_onset
    ##   <dbl>       <dbl> <fct>      <dbl> <fct>                    <dbl>
    ## 1    14        58.4 female        20 APOE4 non-carrier         66.2
    ## 2    49        64.7 male          16 APOE4 non-carrier         68.4
    ## 3    92        68.6 female        20 APOE4 non-carrier         NA  
    ## 4   179        68.1 male          16 APOE4 non-carrier         NA  
    ## 5   268        61.4 female        18 APOE4 carrier             67.5
    ## 6   304        63.8 female        16 APOE4 non-carrier         NA  
    ## 7   389        59.3 female        16 APOE4 non-carrier         NA  
    ## 8   412        67   male          16 APOE4 carrier             NA

By using anti_join(), only 8 observations appear in both datasets are
retained.

``` r
combination_df = 
  inner_join(mci_baseline_df, amyloid_df, by = "id")
write_csv(combination_df,"./data/mci_combination_df.csv")
```

The combination dataset has 471 observations and 11 variables.
