---
title: "p8105_hw2_jr4392"
author: "Junyi Ren"
date: "2023-10-02"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

##Problem 1
```{r}
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |>
  select(year, month, everything(), -day, -prez_dem, -prez_gop)
```

```{r}
snp = 
  read_csv("./fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  select(year, month, close) |>
  mutate(year = ifelse(year >= 50, 1900 + year, 2000+ year)) |>
  mutate(month = month.name[month])
```

```{r}
unemployment = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

```{r}
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

## Problem 2
```{r}
trash_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 1) |>
    janitor::clean_names() |>
    select(-x15, -x16)|>
  head(-1) |>
    mutate(
    homes_powered = weight_tons * 500 / 30) |>
   mutate(year = numeric_version(year))
```

```{r}
professor_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 2) |>
  janitor::clean_names() |>
    head(-1) |>
    mutate(
    homes_powered = weight_tons * 500 / 30) |>
    mutate(year = numeric_version(year))
```

```{r}
gwynnda_data = read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 4) |> 
  janitor::clean_names() |>
  head(-2) |>
  mutate(
    homes_powered = weight_tons * 500 / 30) |>
    mutate(year = numeric_version(year))
```

```{r}
merge_trash_wheel_data = 
  bind_rows(trash_data, professor_data, gwynnda_data)
```
The total weight of trash collected by Professor Trash Wheel is 190.12, the total number of cigarette butts collected by Gwynnda in July of 2021 is 16,300.

## Problem 3
```{r}
baseline_df = 
  read_csv("./data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
        sex, 
        0 ~ "male", 
        1 ~ "female"),
    sex = as.factor(sex), 
    apoe4 = 
      case_match(
        apoe4, 
        0 ~ "APOE4 non-carrier",
        1 ~ "APOE4 carrier"),
    apoe4 = as.factor(apoe4) ) 

mci_baseline_df = 
  baseline_df |>
  mutate(age_at_onset = as.numeric(age_at_onset)) |>
  filter(age_at_onset > current_age | is.na(age_at_onset))
```

```{r}
amyloid_df = 
  read_csv("./data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id  = study_id)
```

```{r}
anti_join(mci_baseline_df, amyloid_df, by = "id")
```

```{r}
combination_df = 
  inner_join(mci_baseline_df, amyloid_df, by = "id")
write_csv(combination_df,"./data/mci_combination_df.csv")
```
